# Generated by Django 5.2.5 on 2025-08-31 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_researchandinnovationimage_research_and_innovation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
