# Generated by Django 5.2.5 on 2025-09-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='test',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
