# Generated by Django 5.2.5 on 2025-09-07 13:38

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_link_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=website.models.category_types, default='research', max_length=255),
        ),
        migrations.AlterField(
            model_name='link',
            name='index',
            field=models.IntegerField(default=0, help_text='Tip : index of link in section starts from 1 (0 to replace all text in section)'),
        ),
    ]
