# Generated by Django 5.2.5 on 2025-09-07 13:39

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_category_type_alter_link_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=website.models.category_types, max_length=255, null=True),
        ),
    ]
