# Generated by Django 5.2.5 on 2025-09-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_article_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_images/')),
                ('image_alternative_text', models.TextField(blank=True, null=True)),
                ('link', models.CharField(max_length=255)),
                ('link_text', models.CharField(max_length=255)),
                ('link_index', models.IntegerField(default=0, help_text='Tip : index of link in section starts from 1 (0 to replace all text in section)')),
            ],
        ),
    ]
