# Generated by Django 5.2.5 on 2025-09-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_homearticle_delete_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='homearticle',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homearticle',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
