# Generated by Django 5.2.5 on 2025-09-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_rename_teammemebr_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
