# Generated by Django 5.2.5 on 2025-09-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_footer_subfooter_subfootercategories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubFooterCategories',
            new_name='SubFooterCategory',
        ),
    ]
