# Generated by Django 5.2.5 on 2025-09-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_newslettersubscription_delete_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriptionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
