# Generated by Django 5.2.5 on 2025-09-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_newslettersubscriptionmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriptionmessage',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
