# Generated by Django 5.2.5 on 2025-09-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_newslettersubscriptionmessage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
