# Generated by Django 5.2.5 on 2025-09-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_article_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
