# Generated by Django 5.2.5 on 2025-10-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_alter_customuser_contact_form_submission_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='articles',
        ),
    ]
