# Generated by Django 5.2.5 on 2025-10-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_remove_newsletterarticle_clickers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterarticle',
            name='custom_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsletterarticle',
            name='custom_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
