# Generated by Django 5.2.5 on 2025-10-14 15:28

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_newsletterarticle_custom_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='custom_html_file',
            field=models.FileField(blank=True, null=True, storage=core.storage.SignedMediaStorage(), upload_to='templates/'),
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
