# Generated by Django 5.2.5 on 2025-09-11 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_footer_homearticle_newslettersubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='redirect_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirect_categories', to='website.article'),
        ),
    ]
