# Generated by Django 5.2.5 on 2025-09-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_category_redirect_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='redirect_tag_id',
            field=models.CharField(blank=True, choices=[('hero', 'Hero tag(first tag in the index page)'), ('footer', 'Footer tag(last tag in the index page)')], max_length=255, null=True),
        ),
    ]
