# Generated by Django 5.2.5 on 2025-09-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_category_redirect_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homearticle',
            name='title',
        ),
        migrations.AddField(
            model_name='homearticle',
            name='type',
            field=models.CharField(blank=True, choices=[('first_article', 'First Article'), ('second_article', 'Second Article')], max_length=255, null=True),
        ),
    ]
