# Generated by Django 5.2.5 on 2025-09-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_homearticle_title_homearticle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homearticle',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homearticle',
            name='link_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homearticle',
            name='type',
            field=models.CharField(blank=True, choices=[('hero', 'Hero Article'), ('about', 'About Article')], max_length=255, null=True),
        ),
    ]
