# Generated by Django 5.2.5 on 2025-09-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_homearticle_link_alter_homearticle_link_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfied_clients', models.IntegerField(blank=True, null=True)),
                ('successful_projects', models.IntegerField(blank=True, null=True)),
                ('scientific_publications', models.IntegerField(blank=True, null=True)),
                ('collaborating_countries', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
