# Generated by Django 5.2.5 on 2025-09-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephones', models.JSONField(blank=True, help_text='Tip : Must be list of telephones as strings like ["+447440449993","+420776858280"]', null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='redirect_tag_id',
            field=models.CharField(blank=True, choices=[('hero', 'Hero tag(first tag in the index page)'), ('footer', 'Footer tag(last tag in the index page)'), ('contact', 'Contact Tag)'), ('counts', 'Counts Tag)'), ('news', 'News Tag)')], max_length=255, null=True),
        ),
    ]
