# Generated by Django 5.2.5 on 2025-09-13 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_contact_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='telephones',
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='website.contact')),
            ],
        ),
        migrations.CreateModel(
            name='ContactRegistrationNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_title1', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_number1', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_title2', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_number2', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_title3', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_number3', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_numbers', to='website.contact')),
            ],
        ),
        migrations.CreateModel(
            name='ContactTelephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telephones', to='website.contact')),
            ],
        ),
    ]
