# Generated by Django 5.2.5 on 2025-09-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_contact_address_remove_contact_telephones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial_images/')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
