# Generated by Django 5.2.5 on 2025-09-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='rate',
            new_name='stars',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='linkedin',
        ),
    ]
