# Generated by Django 5.2.5 on 2025-09-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_collaborator'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('type', models.CharField(choices=[('faqlist1', 'FAQ List 1'), ('faqlist2', 'FAQ List 2')], max_length=255)),
            ],
        ),
    ]
