# Generated by Django 5.2.5 on 2025-09-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_frequentlyaskedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='pin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='redirect_tag_id',
            field=models.CharField(blank=True, choices=[('hero', 'Hero tag(first tag in the index page)'), ('footer', 'Footer tag(last tag in the index page)'), ('contact', 'Contact Tag)'), ('counts', 'Counts Tag)'), ('news', 'News Tag)'), ('clients', 'clients(Collaborators) Tag)'), ('testimonials', 'Testimonials Tag)')], max_length=255, null=True),
        ),
    ]
