# Generated by Django 5.2.5 on 2025-10-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_article_pin_article_pin_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulseHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
