# Generated by Django 5.2.5 on 2025-10-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_pulsehub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
    ]
