# Generated by Django 5.2.5 on 2025-10-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_contactformsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('articles', models.ManyToManyField(related_name='newsletter_articles', to='website.article')),
            ],
        ),
    ]
