# Generated by Django 5.2.5 on 2025-10-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='articles',
            field=models.ManyToManyField(related_name='newsletter_subscription_articles', to='website.article'),
        ),
    ]
