# Generated by Django 5.2.5 on 2025-10-05 13:52

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_newslettersubscription_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_form_submission_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='image',
            field=models.ImageField(storage=core.storage.SignedMediaStorage(), upload_to='collaborator_images/'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storage.SignedMediaStorage(), upload_to='footer_images/'),
        ),
        migrations.AlterField(
            model_name='homearticle',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storage.SignedMediaStorage(), upload_to='home_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storage.SignedMediaStorage(), upload_to='article_images/'),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storage.SignedMediaStorage(), upload_to='section_images/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storage.SignedMediaStorage(), upload_to='team_images/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storage.SignedMediaStorage(), upload_to='testimonial_images/'),
        ),
    ]
