# Generated by Django 5.2.5 on 2025-10-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_customuser_contact_form_submission_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='teeeeeeeeeest'),
        ),
    ]
