# Generated by Django 5.2.5 on 2025-10-10 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_customuser_contact_form_submission_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='articles',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='footer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='header_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='name',
            field=models.CharField(default='mahmoud', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NewsLetterArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_description', models.TextField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.article')),
                ('clickers', models.ManyToManyField(blank=True, to='website.newslettersubscription')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.newsletter')),
            ],
            options={
                'unique_together': {('newsletter', 'article')},
            },
        ),
    ]
