# Generated by Django 5.2.5 on 2025-10-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_remove_newsletter_articles_newsletter_footer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='articles',
            field=models.ManyToManyField(related_name='newsletter_articles', through='website.NewsLetterArticle', to='website.article'),
        ),
    ]
