# Generated by Django 5.2.5 on 2025-10-14 14:48

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_newsletter_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='custom_html_file',
            field=models.FileField(blank=True, null=True, storage=core.storage.SignedMediaStorage(), upload_to='templates/'),
        ),
    ]
