# Generated by Django 5.2.5 on 2025-10-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_category_custom_html_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
