# Generated by Django 5.2.5 on 2025-08-31 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_researchandinnovation_images_sections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Sections',
            new_name='Section',
        ),
    ]
