# Generated by Django 5.2.5 on 2025-08-31 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_images_image_rename_sections_section'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ResearchAndInnovationImage',
        ),
        migrations.RenameModel(
            old_name='Section',
            new_name='ResearchAndInnovationSection',
        ),
    ]
