# Generated by Django 5.2.5 on 2025-09-04 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_customuser_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='test',
        ),
    ]
