# Generated by Django 5.2.5 on 2025-09-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_customuser_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
