# Generated by Django 5.2.5 on 2025-09-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_link_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
