# Generated by Django 5.2.5 on 2025-09-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_link_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='index',
            field=models.IntegerField(default=0, help_text='index of link in section starts from 1 (0 to replace all text in section)'),
        ),
    ]
