# Generated by Django 5.2.5 on 2025-09-07 13:40

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=website.models.category_types, max_length=255),
        ),
    ]
