# Generated by Django 5.2.5 on 2025-09-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alternative_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
