# Generated by Django 5.2.5 on 2025-09-07 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_article_created_at_article_created_by_image_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='digital_twin_model',
            field=models.JSONField(blank=True, help_text='Tip : Must be list of 6 elements(faces)', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='article',
            field=models.ForeignKey(blank=True, help_text='Tip:Leave it blank if you create or update category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.article'),
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Tip:Leave it blank if you create or update article', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_images', to='website.category'),
        ),
    ]
