# Generated by Django 5.2.5 on 2025-09-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_team_teammemebr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMemebr',
            new_name='TeamMember',
        ),
    ]
