# Generated by Django 5.2.5 on 2025-09-09 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_category_redirect_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='footer_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('registered_addresses', models.TextField(blank=True, null=True)),
                ('contact_addresses', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_footers', to='website.footer')),
            ],
        ),
        migrations.CreateModel(
            name='SubFooterCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='website.category')),
                ('sub_footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_footer_categories', to='website.subfooter')),
            ],
        ),
    ]
