# Generated by Django 5.2.5 on 2025-09-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
