# Generated by Django 5.2.5 on 2025-10-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_customuser_contact_form_submission_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_form_submission_recipient',
            field=models.BooleanField(default=False, help_text='If checked, user will receive contact form submission emails'),
        ),
    ]
