# Generated by Django 5.2.5 on 2025-10-06 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_remove_newsletter_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.article')),
                ('clickers', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.newslettersubscription')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.newsletter')),
            ],
            options={
                'unique_together': {('newsletter', 'article')},
            },
        ),
        migrations.AddField(
            model_name='newsletter',
            name='articles',
            field=models.ManyToManyField(related_name='newsletter_articles', through='website.NewsLetterArticle', to='website.article'),
        ),
    ]
