# Generated by Django 5.2.5 on 2025-10-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_newsletterarticle_newsletter_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletterarticle',
            name='clickers',
        ),
        migrations.AddField(
            model_name='newsletterarticle',
            name='clickers',
            field=models.ManyToManyField(to='website.newslettersubscription'),
        ),
    ]
