# Generated by Django 5.2.5 on 2025-10-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_remove_newsletterarticle_clickers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='name',
            field=models.CharField(default='Mahmoud', max_length=255),
            preserve_default=False,
        ),
    ]
