# Generated by Django 5.2.5 on 2025-10-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_newslettersubscription_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='footer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='header_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
