# Generated by Django 5.2.5 on 2025-10-06 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_newsletter_footer_text_newsletter_header_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletterarticle',
            name='clickers',
        ),
        migrations.AlterField(
            model_name='newsletterarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.article'),
        ),
        migrations.AlterField(
            model_name='newsletterarticle',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.newsletter'),
        ),
    ]
