# Generated by Django 5.2.5 on 2025-10-06 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_remove_newsletterarticle_clickers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterarticle',
            name='clickers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.newslettersubscription'),
        ),
    ]
