# Generated by Django 5.2.5 on 2025-10-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_newsletterarticle_clickers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletterarticle',
            name='clickers',
        ),
        migrations.AddField(
            model_name='newsletterarticle',
            name='clickers',
            field=models.ManyToManyField(blank=True, to='website.newslettersubscription'),
        ),
    ]
